import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { SignInButton } from "@clerk/nextjs";
import { SignOutButton } from "@clerk/nextjs";
import { useUser } from "@clerk/nextjs";

export default function Home() {
  const user = useUser()
  const {data} = api.posts.getAll.useQuery()
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
      <div>{!user.isSignedIn && <SignInButton/>}</div>
      <h1 >{user.isSignedIn && <SignOutButton />} </h1>
      <br />
      <h1 >Posts</h1>

      <ul>  
        {data?.map((post) => (
          <li key={post.id}>
              <div>{post.content}</div>
          </li>
        ))}
      </ul>  
      </main>
    </>
  );
}
