import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { SignInButton } from "@clerk/nextjs";
import { SignOutButton } from "@clerk/nextjs";
import { useUser } from "@clerk/nextjs";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const user = useUser()
  console.log(user )
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
      <div className="text-white">{!user.isSignedIn && <SignInButton/>}</div>
      <h1 className="text-white">Hello World</h1>
      <h1 className="text-white">{user.isSignedIn && <SignOutButton />} </h1>
        

        
      </main>
    </>
  );
}
